#!/usr/bin/env python

Import("env")
Import("env_modules")

env_gmake_2d_ide = env_modules.Clone()
module_obj = []

env_gmake_2d_ide.add_source_files(module_obj, "*.cpp")

if env.editor_build:
    env_gmake_2d_ide.add_source_files(module_obj, "editor/*.cpp")

env.modules_sources += module_obj
